MD001: false # MD001/heading-increment
MD007: false # MD007/ul-indent
MD011: false # MD011/no-reversed-links
MD013: false # MD013/line-length
MD024: false # MD024/no-duplicate-heading
MD025: false # MD025/single-title/single-h1
MD026: false # MD026/no-trailing-punctuation
MD028: false # MD028/no-blanks-blockquote
MD029: false # MD029/ol-prefix
MD033: false # MD033/no-inline-html
MD034: false # MD034/no-bare-urls
MD036: false # MD036/no-emphasis-as-heading
MD041: false # MD041/first-line-heading/first-line-h1
MD046: false # MD046/code-block-style
MD050: false # MD050/strong-style
