erDiagram
    %% Каталог библиотечных книг
    authors["Авторы (authors)"] {
        INTEGER    id PK             "Первичный ключ"
        TEXT       first_name        "Имя"
        TEXT       last_name         "Фамилия"
        INTEGER    birth_year        "Год рождения"
    }

    books["Книги (books)"] {
        INTEGER    id PK              "Первичный ключ"
        TEXT       title             "Название"
        INTEGER    publication_year  "Год издания"
        TEXT       isbn              "ISBN"
        TEXT       genre             "Жанр"
        INTEGER    author_id FK      "Автор"
        INTEGER    pages             "Кол-во страниц"
        INTEGER    available_copies  "Доступно экземпляров"
    }

    authors ||--o{ books : "пишут"
